#! /bin/bash

#  Set GPIO17 high to enable the Wiznet chip
raspi-gpio set 17 op
raspi-gpio set 17 dh

#  Read CPU serial number
serial=$(tr -d '\0' </sys/firmware/devicetree/base/serial-number)
serial1=${serial:10:2}
serial2=${serial:12:2}
serial3=${serial:14:2}
#  Use prefix allocated to the Raspberry Pi Foundation
addrleft=b8:27:eb:
colon=:

#  Construct Ethernet MAC address from CPU serial number
addr="$addrleft$serial1$colon$serial2$colon$serial3"
echo $addr
sudo dtoverlay spi1-3cs cs0_spidev=disable cs1_spidev=disable cs2_spidev=disable
sudo dtoverlay w5500-spi1 int_pin=25 cs=0 mac=$addr

sleep 20

# Add the network interfaces to the bridge
sudo brctl addif br0 eth0
